### ISSUE TITLE
在rn0.62.2版本安卓上面用这个组件报错

### ISSUE THREAD

**Issue by zzz62755** [superchenwb/react-native-linear-animated-gradient-transition#2]
报红字typeError：Cannot assign to read only property 'animation' of object '#<OBject>'，把新增的useNativeDriver: true,和useNativeDriver: animation.useNativeDriver删除就能用，但是报黄字没有使用useNativeDriver

**Comment by superchenwb** [comment]
升级到了0.1.6版本
